# Rebuild the source code only when needed
FROM node:alpine
WORKDIR /app

ENV NODE_ENV development

EXPOSE 3000

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
# RUN npx next telemetry disable

CMD ["yarn", "dev"]/

